_wandb:
    value:
        cli_version: 0.22.0
        e:
            9uunzu7a07e82ysounf4y4tj8fk4h50r:
                codePath: e2e_imaging.ipynb
                codePathLocal: e2e_imaging.ipynb
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "982003838976"
                        used: "830222979072"
                email: mathewjulia06@gmail.com
                executable: /home/jmathew_waller/workspace/env/bin/python
                git:
                    commit: b774ea3bc496a93fd7d6056332d98dba6ab9c3b4
                    remote: git@github.com:Drizlly/e2e-imaging.git
                gpu: NVIDIA TITAN Xp
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-2fb481ce-8d12-dc18-aae1-ecc4e8cea0fb
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-bb23b15e-f6d2-e544-c5ee-48f9afd3acca
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-62071dc0-6968-403f-a659-439defd3d461
                    - architecture: Pascal
                      cudaCores: 3840
                      memoryTotal: "12884901888"
                      name: NVIDIA TITAN Xp
                      uuid: GPU-c1e81f76-f7cb-2f14-4d4e-7da18016bad2
                host: CIVO-ML-SERVER
                memory:
                    total: "99910496256"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.35
                program: /home/jmathew_waller/workspace/e2e-imaging/e2e_imaging.ipynb
                python: CPython 3.11.13
                root: /home/jmathew_waller/workspace/e2e-imaging
                startedAt: "2026-02-25T09:56:50.949679Z"
                writerId: 9uunzu7a07e82ysounf4y4tj8fk4h50r
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 53
            "2":
                - 2
                - 3
                - 5
                - 12
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.13
            "5": 0.22.0
            "8":
                - 1
            "12": 0.22.0
            "13": linux-x86_64
dataset:
    value:
        batch_size: 32
        dataset_name: mnist
        photon_count: 160
        subset_fraction: 0.01
        tile_cols: 1
        tile_rows: 1
general:
    value:
        seed_value: 0
logging:
    value:
        log_every: 10
        project_name: e2e_imaging_playground
        run_name: mnist_photon_count_160_num_gaussian_10_photon_count_160
        use_wandb: true
optimization:
    value:
        initial log_K: "-1.0"
        learning_rate: 0.001
psf_layer:
    value:
        num_gaussian: 10
        object_size: 32
        psf_size:
            - 32
            - 32
